// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWjbW0LMIMLvAUzfA7yr8g9wfacGXWyPA',
    appId: '1:330795856822:web:ac628af89b446736748717',
    messagingSenderId: '330795856822',
    projectId: 'cashmeup-a872c',
    authDomain: 'cashmeup-a872c.firebaseapp.com',
    storageBucket: 'cashmeup-a872c.firebasestorage.app',
    measurementId: 'G-ZDTBRFFR1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0f-C6XFYdVIRFPRas2xt-kiT6jM_yhBc',
    appId: '1:330795856822:android:15a2274eff0ab40d748717',
    messagingSenderId: '330795856822',
    projectId: 'cashmeup-a872c',
    storageBucket: 'cashmeup-a872c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdG9-6yE8H-8Nj9JZYrSjdZj7g7d6HhUI',
    appId: '1:330795856822:ios:212b9284c6ac86f1748717',
    messagingSenderId: '330795856822',
    projectId: 'cashmeup-a872c',
    storageBucket: 'cashmeup-a872c.firebasestorage.app',
    iosBundleId: 'com.example.cashmeup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdG9-6yE8H-8Nj9JZYrSjdZj7g7d6HhUI',
    appId: '1:330795856822:ios:212b9284c6ac86f1748717',
    messagingSenderId: '330795856822',
    projectId: 'cashmeup-a872c',
    storageBucket: 'cashmeup-a872c.firebasestorage.app',
    iosBundleId: 'com.example.cashmeup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWjbW0LMIMLvAUzfA7yr8g9wfacGXWyPA',
    appId: '1:330795856822:web:47500aa742fc6cc4748717',
    messagingSenderId: '330795856822',
    projectId: 'cashmeup-a872c',
    authDomain: 'cashmeup-a872c.firebaseapp.com',
    storageBucket: 'cashmeup-a872c.firebasestorage.app',
    measurementId: 'G-12T4BM9E5J',
  );
}
